Mark deprecated SSL settings as obsolete
logstash-plugins/logstash-input-tcp pull request #228
Opened 2024-12-02 14:50 UTC by robbavey

This commit marks the following SSL settings as obsolete:

`ssl_cert`, which should be replaced by `ssl_certificate`
`ssl_enable`, which should be replaced by `ssl_enabled`
`ssl_verify`, which should be replaced by `ssl_client_authentication` when `mode` is `server` or `ssl_verification_mode`when mode is `client`

Relates: https://github.com/logstash-plugins/logstash-input-tcp/issues/225

2024-12-09 21:00 UTC, donoghuc commented on CHANGELOG.md
> +    - [xxx](https://github.com/logstash-plugins/logstash-input-tcp/pull/xxx)
```suggestion
    - [228](https://github.com/logstash-plugins/logstash-input-tcp/pull/228)
```

2024-12-09 21:01 UTC, donoghuc commented on docs/index.asciidoc
> +WARNING: As of version `6.0.0` of this plugin, the following configuration options are no longer available,
```suggestion
WARNING: As of version `7.0.0` of this plugin, the following configuration options are no longer available,
```

2024-12-09 21:03 UTC, donoghuc requested changes
Just a couple small docs comments. Code removal looks clean.

2024-12-09 21:38 UTC, robbavey commented on CHANGELOG.md
> +    - [xxx](https://github.com/logstash-plugins/logstash-input-tcp/pull/xxx)
🤦‍♂️

2024-12-09 22:29 UTC, donoghuc approved these changes
LGTM

2024-12-09 23:58 UTC, donoghuc commented on spec/inputs/tcp_spec.rb
> +  describe 'handling obsolete settings for server mode' do
I'm missing how this is different from client mode?

2024-12-10 20:34 UTC, donoghuc approved these changes
Assuming CI is green i think this is good! Apologies for not catching everything on the first take 😬

2024-12-10 20:40 UTC, robbavey commented
> Assuming CI is green i think this is good! Apologies for not catching everything on the first take 😬

All good! Thanks for being thorough and catching all of my 🤦 ...

2024-12-10 21:12 UTC, robbavey commented
Ready for doc review @karenzone

2024-12-23 18:10 UTC, karenzone approved these changes
LGTM

2024-12-23 18:20 UTC, karenzone reviewed
Updated text to align with messaging for other plugins

2024-12-23 18:20 UTC, karenzone commented on docs/index.asciidoc
> +WARNING: As of version `7.0.0` of this plugin, the following configuration options are no longer available,
WARNING: As of version `7.0.0` of this plugin, some configuration options have been replaced.
The plugin will fail to start if it contains any of these obsolete options.

2024-12-23 18:21 UTC, karenzone reviewed
Suggestion inline

2024-12-23 18:21 UTC, karenzone commented on docs/index.asciidoc
> +and have been replaced by the following options:
```suggestion
WARNING: As of version `6.0.0` of this plugin, some configuration options have been replaced.
The plugin will fail to start if it contains any of these obsolete options. 
```

2025-01-03 18:24 UTC, robbavey commented
Ready for another round @karenzone

2025-01-09 23:29 UTC, karenzone approved these changes
LGTM

2025-01-09 23:29 UTC, karenzone approved these changes
LGTM

2025-01-10 19:30 UTC, merged